image: fedora:27

stages:
  - build

before_script:
  - dnf install -y gcc gettext glib2-devel gobject-introspection-devel gtk-doc meson ninja-build

build-json-glib:
  stage: build
  script:
    - meson --prefix /usr -Dman=true _build .
    - cd _build
    - ninja
    - meson test
  except:
    - tags
  artifacts:
    when: on_failure
    name: "json-glib-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
